# Generated by Django 4.0.2 on 2022-02-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaliqliTaomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoshtliTaomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ichimliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('size', models.CharField(choices=[('0.5L', '0.5L'), ('1L', '1L'), ('1.5L', '1.5L')], default='0.5L', max_length=5, null=True)),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('typepizza', models.CharField(choices=[('SIRLIK', 'Sirlik'), ('QOZIQORINLIK', "Qo'ziqorinlik"), ('MARGORITA', 'Margorita')], default='Sirlik', max_length=50)),
                ('sizepizza', models.CharField(choices=[('KATTA', 'Katta'), ('STANDART', 'Standart'), ('KICHIK', 'Kichik')], default='Standart', max_length=50)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QaynoqTaomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuyuqTaomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='YaxnaTaomlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('weight', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
