# Generated by Django 4.0.2 on 2022-03-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taomlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baliqlitaomlar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='goshtlitaomlar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ichimliklar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='qaynoqtaomlar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='suyuqtaomlar',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='yaxnataomlar',
            options={'ordering': ['name']},
        ),
    ]
