# Generated by Django 4.0.2 on 2022-02-28 19:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=13)),
                ('delivery_type', models.CharField(choices=[('YETKAZIBBERISH', 'Yetkazib berish'), ('BORIB_OLISH', 'Borib olish')], default='Yetkazib berish', max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('street', models.CharField(max_length=250)),
                ('flat', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=250)),
                ('payment', models.CharField(choices=[('KARTA_ORQALI', 'Karta orqali'), ('NAQD_PUL', 'Naqd pul')], default='Naqd pul', max_length=100)),
                ('call', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuyurtmaJadval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[], max_length=250)),
                ('count', models.IntegerField(default=1)),
                ('price', models.CharField(choices=[], max_length=50)),
                ('date', models.DateField(blank=True, default=datetime.datetime(2022, 3, 1, 0, 27, 6, 744601))),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyurtmalar.buyurtma')),
            ],
            options={
                'ordering': ['buyurtma'],
            },
        ),
    ]
