# Generated by Django 4.0.2 on 2022-03-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0003_savatcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyurtmajadval',
            name='name',
            field=models.CharField(choices=[('CHICAGO PIZZA', 'Chicago pizza')], max_length=250),
        ),
        migrations.AlterField(
            model_name='buyurtmajadval',
            name='price',
            field=models.CharField(choices=[('50000.0', '50000.0')], max_length=50),
        ),
        migrations.AlterField(
            model_name='savatcha',
            name='mahsulot',
            field=models.CharField(choices=[('CHICAGO PIZZA', 'Chicago pizza')], max_length=250),
        ),
    ]
