# Generated by Django 4.0.2 on 2022-03-02 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0004_alter_buyurtmajadval_name_alter_buyurtmajadval_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyurtmajadval',
            name='count',
        ),
        migrations.RemoveField(
            model_name='buyurtmajadval',
            name='name',
        ),
        migrations.RemoveField(
            model_name='buyurtmajadval',
            name='price',
        ),
        migrations.AddField(
            model_name='buyurtmajadval',
            name='basket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buyurtmalar.savatcha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyurtmajadval',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savatcha',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
