# Generated by Django 4.0.2 on 2022-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyurtmalar', '0005_remove_buyurtmajadval_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyurtmajadval',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='savatcha',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
